// apps/frontend/src/routes/_auth/sign-up.tsx
import { useState } from 'react'
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { AlertCircle, Loader2 } from 'lucide-react'

import { useRegisterEmail } from '#/hooks/use-auth'
import { Alert, AlertDescription } from '#/components/ui/alert'
import { Button } from '#/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'
import { Input } from '#/components/ui/input'
import { Label } from '#/components/ui/label'

export const Route = createFileRoute('/_auth/sign-up')({
  component: SignUpPage,
})

function SignUpPage() {
  const navigate = useNavigate()
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [nameManuallyEdited, setNameManuallyEdited] = useState(false)

  const registerMutation = useRegisterEmail({
    onSuccess: () => {
      void navigate({ to: '/' })
    },
    onError: (err) => {
      setError(err.message || 'An unknown error occurred')
    },
  })

  function handleEmailChange(e: React.ChangeEvent<HTMLInputElement>) {
    const newEmail = e.target.value
    setEmail(newEmail)

    if (!nameManuallyEdited) {
      setName(newEmail.split('@')[0] ?? '')
    }
  }

  function handleNameChange(e: React.ChangeEvent<HTMLInputElement>) {
    setName(e.target.value)
    setNameManuallyEdited(true)
  }

  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    setError(null)
    registerMutation.mutate({ name, email, password })
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Sign Up</CardTitle>
        <CardDescription>Create an account</CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="flex flex-col gap-4">
          {error && (
            <Alert variant="destructive">
              <AlertCircle className="size-4" />
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          <div className="flex flex-col gap-2">
            <Label htmlFor="name">Name</Label>
            <Input
              id="name"
              type="text"
              placeholder="Enter your name"
              value={name}
              onChange={handleNameChange}
              required
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              placeholder="Enter your email"
              value={email}
              onChange={handleEmailChange}
              required
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              placeholder="Enter your password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>

          <Button type="submit" disabled={registerMutation.isPending} size="lg" className="w-full">
            {registerMutation.isPending && <Loader2 className="animate-spin" />}
            Sign Up
          </Button>

          <p className="text-center text-sm text-muted-foreground">
            Already have an account?{' '}
            <Link to="/sign-in" className="text-primary font-medium hover:underline">
              Sign in
            </Link>
          </p>
        </form>
      </CardContent>
    </Card>
  )
}

// apps/web/src/pages/auth/sign-up.vue
<script setup lang="ts">
import type { AuthFormField, FormSubmitEvent } from '@nuxt/ui'
import { ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import * as z from 'zod'
import { useRegisterEmail } from '@/composables/use-auth'

const router = useRouter()
const route = useRoute()
const redirectTo = route.query.redirectTo as string | undefined
const loading = ref(false)
const error = ref<string | null>(null)
const { mutate } = useRegisterEmail({
  onMutate: () => {
    loading.value = true
    error.value = null // Clear previous errors
  },
  onError: (e) => {
    loading.value = false
    if (e instanceof Error) {
      error.value = e.message
    } else {
      error.value = 'An unknown error occurred'
    }
  },
  onSuccess: () => {
    loading.value = false
    router.push(redirectTo || '/')
  },
})

const fields: AuthFormField[] = [
  {
    name: 'email',
    type: 'email',
    label: 'Email',
    placeholder: 'Enter your email',
    required: true,
  },
  {
    name: 'password',
    type: 'password',
    label: 'Password',
    placeholder: 'Enter your password',
    required: true,
  },
]

const schema = z.object({
  email: z.email('Invalid email'),
  password: z.string('Password is required').min(8, 'Password must be at least 8 characters long'),
})

type Schema = z.output<typeof schema>

async function onSubmit(payload: FormSubmitEvent<Schema>) {
  const { data } = payload

  mutate({
    email: data.email,
    password: data.password,
    name: data.email.split('@')[0] ?? data.email,
  })
}
</script>

<template>
  <div class="flex flex-col items-center justify-center gap-4 p-4 h-screen">
    <UPageCard class="w-full max-w-md">
      <UAuthForm
        :schema="schema"
        title="Register"
        description="Create a new account"
        icon="i-lucide-user"
        :fields="fields"
        @submit="onSubmit"
      >
        <template #validation>
          <UAlert v-if="error" color="error" icon="i-lucide-triangle-alert" :title="error" />
        </template>

        <template #description>
          Already have an account?
          <ULink to="/auth" class="text-primary font-medium">Sign in</ULink>.
        </template>
      </UAuthForm>
    </UPageCard>
  </div>
</template>
