// apps/web/src/pages/auth/sign-in.vue
<script setup lang="ts">
import type { AuthFormField, FormSubmitEvent } from '@nuxt/ui'
import { ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import * as z from 'zod'
import { useLoginEmail } from '@/composables/use-auth'

const router = useRouter()
const route = useRoute()
const redirectTo = route.query.redirectTo as string | undefined
const loading = ref(false)
const error = ref<string | null>(null)

const { mutate } = useLoginEmail({
  onMutate: () => {
    loading.value = true
    error.value = null // Clear previous errors
  },
  onError: (e) => {
    loading.value = false
    if (e instanceof Error) {
      error.value = e.message
    } else {
      error.value = 'An unknown error occurred'
    }
  },
  onSuccess: (data) => {
    loading.value = false
    router.push(redirectTo || '/')
  },
})

const fields: AuthFormField[] = [
  {
    name: 'email',
    type: 'email',
    label: 'Email',
    placeholder: 'Enter your email',
    required: true,
  },
  {
    name: 'password',
    type: 'password',
    label: 'Password',
    placeholder: 'Enter your password',
    required: true,
  },
]

const schema = z.object({
  email: z.email('Invalid email'),
  password: z.string('Password is required').min(8, 'Password must be at least 8 characters long'),
})

type Schema = z.output<typeof schema>

async function onSubmit(payload: FormSubmitEvent<Schema>) {
  const { data } = payload
  mutate({
    email: data.email,
    password: data.password,
  })
}
</script>

<template>
  <div class="flex flex-col items-center justify-center gap-4 p-4 h-screen">
    <UPageCard class="w-full max-w-md">
      <UAuthForm
        :schema="schema"
        title="Login"
        description="Enter your credentials to access your account."
        icon="i-lucide-user"
        :fields="fields"
        :loading="loading"
        @submit="onSubmit"
      >
        <template #validation>
          <UAlert v-if="error" color="error" icon="i-lucide-triangle-alert" :title="error" />
        </template>

        <template #description>
          Don't have an account?
          <ULink to="/auth/sign-up" class="text-primary font-medium">Sign up</ULink>.
        </template>
      </UAuthForm>
    </UPageCard>
  </div>
</template>

// apps/frontend/src/routes/_auth/sign-in.tsx
import { useState } from 'react'
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { CircleAlert, Loader2 } from 'lucide-react'

import { Alert, AlertTitle } from '#/components/ui/alert'
import { Button } from '#/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '#/components/ui/card'
import { Input } from '#/components/ui/input'
import { Label } from '#/components/ui/label'
import { useLoginEmail } from '#/hooks/use-auth'

export const Route = createFileRoute('/_auth/sign-in')({
  validateSearch: (search: Record<string, unknown>) => ({
    redirectTo: (search.redirectTo as string) || '',
  }),
  component: SignInPage,
})

function SignInPage() {
  const navigate = useNavigate()
  const { redirectTo } = Route.useSearch()

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const loginMutation = useLoginEmail({
    onSuccess: () => {
      navigate({ to: redirectTo || '/' })
    },
  })

  const errorMessage = loginMutation.error?.message

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    loginMutation.mutate({ email, password })
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-xl">Sign In</CardTitle>
        <CardDescription>Enter your credentials to access your account.</CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="flex flex-col gap-4">
          {errorMessage && (
            <Alert variant="destructive">
              <CircleAlert className="size-4" />
              <AlertTitle>{errorMessage}</AlertTitle>
            </Alert>
          )}

          <div className="flex flex-col gap-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              placeholder="Enter your email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              placeholder="Enter your password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>

          <Button type="submit" disabled={loginMutation.isPending} size="lg" className="w-full">
            {loginMutation.isPending && <Loader2 className="animate-spin" />}
            Sign In
          </Button>

          <p className="text-center text-sm text-muted-foreground">
            Don&apos;t have an account?{' '}
            <Link to="/sign-up" className="text-primary font-medium hover:underline">
              Sign up
            </Link>
          </p>
        </form>
      </CardContent>
    </Card>
  )
}
