// apps/frontend/src/components/user-menu.tsx
import { LogOut } from 'lucide-react'
import { useNavigate } from '@tanstack/react-router'

import { useAuthUser, useLogout } from '#/hooks/use-auth'
import { ThemeModeToggle } from '#/components/theme-mode-toggle'
import { Button } from '#/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '#/components/ui/dropdown-menu'

export function UserMenu() {
  const { data: authUser } = useAuthUser()
  const navigate = useNavigate()
  const logout = useLogout({
    onSuccess: () => {
      navigate({ to: '/sign-in' })
    },
  })

  const userName = authUser?.user.name || 'User'
  const userEmail = authUser?.user.email || ''
  const userInitial = userName[0].toUpperCase()

  return (
    <div className="flex items-center gap-2">
      <ThemeModeToggle />
      <DropdownMenu>
        <DropdownMenuTrigger render={<Button variant="ghost" size="icon" />}>
          <div className="flex size-6 items-center justify-center rounded-full bg-primary text-xs font-medium text-primary-foreground">
            {userInitial}
          </div>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" side="top" sideOffset={8}>
          <DropdownMenuLabel>{userName}</DropdownMenuLabel>
          <DropdownMenuLabel>{userEmail}</DropdownMenuLabel>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={() => logout.mutate()}>
            <LogOut className="mr-2 size-3.5" />
            Log out
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  )
}

// apps/web/src/components/UserMenu.vue
<script setup lang="ts">
import type { DropdownMenuItem } from '@nuxt/ui'
import { computed } from 'vue'
import { useAuthUser } from '@/composables/use-auth'
import { authClient } from '@/lib/auth-client'

const { data: authUser } = useAuthUser()

const user = computed(() => ({
  name: authUser.value?.user.name || 'User',
  email: authUser.value?.user.email || '',
  avatar: authUser.value?.user.name?.[0]?.toUpperCase() || 'U',
}))

const items = computed<DropdownMenuItem[][]>(() => [
  [
    {
      type: 'label',
      label: user.value.name,
      avatar: {
        text: user.value.avatar,
      },
    },
  ],
  [
    {
      label: 'Log out',
      icon: 'i-lucide-log-out',
      onSelect: async () => {
        await authClient.signOut({
          fetchOptions: {
            onSuccess: () => {
              window.location.href = '/auth'
            },
          },
        })
      },
    },
  ],
])
</script>

<template>
  <UDropdownMenu :items="items">
    <UButton color="neutral" variant="ghost" class="justify-start gap-2">
      <template #leading>
        <UAvatar :text="user.avatar" :alt="user.name" size="xs" />
      </template>
      <template #default>
        <span class="truncate">{{ user.name }}</span>
      </template>
    </UButton>
  </UDropdownMenu>
</template>
