// apps/frontend/src/routes/_dashboard/tasks.tsx
import { createFileRoute } from '@tanstack/react-router'
import { TaskInput } from '#/components/tasks/task-input'
import { TaskItem } from '#/components/tasks/task-item'
import { TaskList } from '#/components/tasks/task-list'
import useCreateTask from '#/hooks/queries/use-create-task'
import useDeleteTask from '#/hooks/queries/use-delete-task'
import useTasks from '#/hooks/queries/use-tasks'
import useUpdateTask from '#/hooks/queries/use-update-task'
import type { Task } from '#/types/task'

export const Route = createFileRoute('/_dashboard/tasks')({
  component: TasksPage,
})

function TasksPage() {
  const { data: tasks, isLoading } = useTasks()
  const createTaskMutation = useCreateTask()
  const updateTaskMutation = useUpdateTask()
  const deleteTaskMutation = useDeleteTask()

  const handleCreateTask = (title: string) => {
    createTaskMutation.mutate({ title })
  }

  const handleToggleTask = (task: Task) => {
    updateTaskMutation.mutate({
      id: task.id,
      json: {
        title: task.title,
        completed: !task.completed,
      },
    })
  }

  const handleDeleteTask = (id: string) => {
    deleteTaskMutation.mutate(id)
  }

  return (
    <div className="mx-auto max-w-2xl p-4">
      <h1 className="mb-6 text-2xl font-bold">Tasks</h1>
      <div className="space-y-6">
        <TaskInput onCreate={handleCreateTask} />

        <TaskList tasks={tasks ?? []} isLoading={isLoading}>
          {tasks?.map((task) => (
            <TaskItem
              key={task.id}
              task={task}
              onToggle={() => handleToggleTask(task)}
              onDelete={handleDeleteTask}
            />
          ))}
        </TaskList>
      </div>
    </div>
  )
}

// apps/web/src/pages/tasks.vue
<script setup lang="ts">
import TodoInput from "@/components/TodoInput.vue";
import TodoItem from "@/components/TodoItem.vue";
import TodoList from "@/components/TodoList.vue";
import useCreateTask from "@/composables/queries/use-create-task";
import useDeleteTask from "@/composables/queries/use-delete-task";
import useTasks from "@/composables/queries/use-tasks";
import useUpdateTask from "@/composables/queries/use-update-task";
import type { Task } from "@/types/task";

const { data: tasks, isLoading } = useTasks();
const createTaskMutation = useCreateTask();
const updateTaskMutation = useUpdateTask();
const deleteTaskMutation = useDeleteTask();

const handleCreateTask = (title: string) => {
  createTaskMutation.mutate({ title });
};

const handleToggleTask = (task: Task) => {
  updateTaskMutation.mutate({
    id: task.id,
    json: {
      title: task.title,
      completed: !task.completed,
    },
  });
};

const handleDeleteTask = (id: string) => {
  deleteTaskMutation.mutate(id);
};
</script>

<template>
  <UDashboardPanel>
    <template #header>
      <UDashboardNavbar title="Home" :ui="{ right: 'gap-3' }">
        <template #leading>
          <UDashboardSidebarCollapse />
        </template>
      </UDashboardNavbar>
    </template>

    <template #body>
      <div class="space-y-6 p-4">
        <TodoInput @create="handleCreateTask" />

        <TodoList :tasks="tasks ?? []" :is-loading="isLoading">
          <TodoItem
            v-for="task in tasks"
            :key="task.id"
            :task="task"
            @toggle="handleToggleTask(task)"
            @delete="handleDeleteTask"
          />
        </TodoList>
      </div>
    </template>
  </UDashboardPanel>
</template>
